//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Recruitments
    {
        public int Id { get; set; }
        public int CV_ID { get; set; }
        public int Recruitment_ID { get; set; }
        public System.DateTime Date_Apply { get; set; }
        public int CV_Status { get; set; }
        public Nullable<System.DateTime> Date_Interview { get; set; }
        public string Recruiter_Interview { get; set; }
        public string Notes { get; set; }
        public string Address_Interview { get; set; }
        public string CV_Content { get; set; }
        public Nullable<System.DateTime> Date_Complete { get; set; }
        public Nullable<System.DateTime> Date_Work { get; set; }
        public string Address_Work { get; set; }
        public Nullable<bool> Student_Confirm { get; set; }
        public Nullable<bool> Employer_Confirm { get; set; }
        public string Reason { get; set; }
    
        public virtual CV_Info CV_Info { get; set; }
        public virtual Recruitment Recruitment { get; set; }
        public virtual Status_CV Status_CV { get; set; }
    }
}
