//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models {
    using System;
    using System.Collections.Generic;

    public partial class Company_Info {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Info() {
            this.Faculties_In_Companies = new HashSet<Faculties_In_Companies>();
            this.Recruitments = new HashSet<Recruitment>();
            this.User_In_Company = new HashSet<User_In_Company>();
        }

        public int Id { get; set; }
        public string Name_Company { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Phone { get; set; }
        public string Introduce_Company { get; set; }
        public string website_Company { get; set; }
        public int Province_ID { get; set; }
        public int District_ID { get; set; }
        public System.DateTime Created_at { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public string Slug_Company { get; set; }
        public Nullable<int> Is_hot_Company { get; set; }
        public string Faculties_Other { get; set; }
        public string Address_Company { get; set; }
        public Nullable<int> Status { get; set; }
        public int[] FacRec { get; set; }
        public string Token { get; set; }
        public string Code { get; set; }
        public string Representative { get; set; }
        public Nullable<int> Scale_from { get; set; }
        public Nullable<int> Scale_to { get; set; }
        public string Scale_Range { get; set; }

        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual Status_Company Status_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faculties_In_Companies> Faculties_In_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_In_Company> User_In_Company { get; set; }
    }
}
