//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmation_intern
    {
        public int id { get; set; }
        public string student_name { get; set; }
        public string student_id { get; set; }
        public string student_class { get; set; }
        public int faculty_id { get; set; }
        public string school_year { get; set; }
        public int major_id { get; set; }
        public Nullable<int> level_id { get; set; }
        public string cellphone { get; set; }
        public string student_email { get; set; }
        public string student_street { get; set; }
        public string student_ward { get; set; }
        public int student_district_id { get; set; }
        public int student_province_id { get; set; }
        public int type_intern { get; set; }
        public string other_type_intern { get; set; }
        public int semester { get; set; }
        public string position { get; set; }
        public string department { get; set; }
        public System.DateTime start_day { get; set; }
        public System.DateTime end_day { get; set; }
        public string schedule_work { get; set; }
        public string organization_name { get; set; }
        public string website { get; set; }
        public Nullable<int> tax { get; set; }
        public string org_telephone { get; set; }
        public string org_street { get; set; }
        public string org_ward { get; set; }
        public int org_district_id { get; set; }
        public int org_province_id { get; set; }
        public string human_resource_name { get; set; }
        public string human_resource_position { get; set; }
        public string human_resource_position_tel { get; set; }
        public string human_resource_email { get; set; }
        public string human_resource_cel { get; set; }
        public string supervisor_name { get; set; }
        public string supervisor_position { get; set; }
        public string supervisor_tel { get; set; }
        public string supervisor_email { get; set; }
        public string supervisor_cellphone { get; set; }
        public System.DateTime create_day { get; set; }
        public string link { get; set; }
        public string account_id { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Faculties_Majors Faculties_Majors { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual District District1 { get; set; }
        public virtual Province Province1 { get; set; }
    }
}
