//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CV_Info()
        {
            this.Apply_Recruitments = new HashSet<Apply_Recruitments>();
        }
    
        public int ID { get; set; }
        public int Student_Id { get; set; }
        public string Personal_Goal { get; set; }
        public string About_Student { get; set; }
        public Nullable<int> CV_Template_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply_Recruitments> Apply_Recruitments { get; set; }
        public virtual Student_Info Student_Info { get; set; }
    }
}
