//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Configs
    {
        public int Id { get; set; }
        public string EmailSubject { get; set; }
        public string Content_Header { get; set; }
        public string Content_Footer { get; set; }
        public string Signature { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Email_Type { get; set; }
    }
}
