//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculties_In_Companies
    {
        public int Id { get; set; }
        public int Company_Id { get; set; }
        public int Faculty_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        public virtual Company_Info Company_Info { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
