//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public int Level_Id { get; set; }
        public int Major_Id { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> Type_Inter { get; set; }
        public int Semester_Inter { get; set; }
        public System.DateTime Inter_from { get; set; }
        public System.DateTime Inter_to { get; set; }
        public string School_year { get; set; }
        public string internTypeOther { get; set; }
        public string Class { get; set; }
        public string MSSV { get; set; }
        public int status { get; set; }
        public System.DateTime create_day { get; set; }
    
        public virtual Faculties_Majors Faculties_Majors { get; set; }
    }
}
