//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intership
    {
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public int Level_Id { get; set; }
        public int Major_ID { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Company_Name { get; set; }
        public string Type_Inter { get; set; }
        public int Semester_Inter { get; set; }
        public System.DateTime Inter_from { get; set; }
        public System.DateTime Inter_to { get; set; }
        public string School_year { get; set; }
    
        public virtual Faculties_Majors Faculties_Majors { get; set; }
    }
}
