//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Info
    {
        public int Id { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_PhoneNumber { get; set; }
        public Nullable<System.DateTime> Staff_Create_at { get; set; }
        public Nullable<System.DateTime> Staff_Update_at { get; set; }
        public int Status_Id { get; set; }
        public string Account_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Status_Account Status_Account { get; set; }
    }
}
