//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Projects
    {
        public int Id { get; set; }
        public int Student_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Date_Start { get; set; }
        public string Date_End { get; set; }
    
        public virtual Student_Info Student_Info { get; set; }
    }
}
