//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Info()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.CV_Info = new HashSet<CV_Info>();
            this.CV_Publics = new HashSet<CV_Publics>();
            this.Student_Certificates = new HashSet<Student_Certificates>();
            this.Student_Projects = new HashSet<Student_Projects>();
            this.Student_Skills = new HashSet<Student_Skills>();
            this.Student_Work_Experiences = new HashSet<Student_Work_Experiences>();
        }
    
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Faculties_Id { get; set; }
        public Nullable<System.DateTime> Student_Birthday { get; set; }
        public Nullable<bool> Student_Gender { get; set; }
        public string Student_Address { get; set; }
        public string Student_PhoneNumber { get; set; }
        public string Student_Photo { get; set; }
        public Nullable<System.DateTime> Student_Create_at { get; set; }
        public Nullable<System.DateTime> Student_Update_at { get; set; }
        public int Status_Id { get; set; }
        public string Account_Id { get; set; }
        public string Student_Id { get; set; }
        public string Student_Class { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV_Info> CV_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV_Publics> CV_Publics { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Status_Account Status_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Certificates> Student_Certificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Projects> Student_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Skills> Student_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Work_Experiences> Student_Work_Experiences { get; set; }
    }
}
