//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_In_Faculties
    {
        public int ID_Tag { get; set; }
        public int ID_Faculties { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
