//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags_Recruitments
    {
        public int Id_Tags { get; set; }
        public int Id_Recruitment { get; set; }
        public Nullable<System.DateTime> Craeted_date { get; set; }
    
        public virtual Recruitment Recruitment { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
