//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_In_Actions
    {
        public string Account_Id { get; set; }
        public int Action_Id { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
